/* Kurátorský katalog fediverse aplikací pro Fedík.online — Pohled 2 „Aplikace“.
   RUČNĚ EDITOVATELNÝ. Vznikl z generate-apps.mjs (FediDB communityDB, MIT, © Daniel Supernault)
   + jednorázová kurace. Re-seed: spusť generate-apps.mjs → web/apps.generated.js a dorovnej.

   contentType id = web/taxonomy.js (jeden slovník typů obsahu).
   description = EN (z communityDB), descriptionCs = český překlad (karta volí dle jazyka).
   Živá čísla (users/instances/growth) sem NEPATŘÍ — doplňuje je bin/refresh_app_stats.rb
   z FediDB API přes 'fedidbSlug' do web/data/app-stats.json; karta je páruje za běhu.

   STAV KURACE:
   • czechUI: „ano“ jen mastodon + pixelfed (ověřeno přeložené); zbytek „ne“ — uprav, až zjistíš jinak.
   • devStatus: část má „unknown“.
   • yearAdded: rok vzniku (žebříček „Nové projekty“); nejisté = null.
   • include:false = infrastruktura/mosty + vědomě vyřazené (manyfold=3D, badgefed=odznaky). */
window.FEDIK_APPS = [
  {
    "id": "pixelfed",
    "fedidbSlug": "pixelfed",
    "name": "Pixelfed",
    "description": "Photo Sharing. For Everyone.",
    "descriptionCs": "Sdílení fotek. Pro každého.",
    "license": "AGPL",
    "website": "https://pixelfed.org",
    "sourceCode": "https://github.com/pixelfed/pixelfed",
    "joinUrl": "https://pixelfed.org/servers",
    "appsUrl": "https://pixelfed.org/mobile-apps",
    "contentType": "photos",
    "logoUrl": "img/logos/pixelfed.png",
    "protocol": "ActivityPub",
    "yearAdded": 2018,
    "centralizedEquivalent": "Instagram",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "mastodon",
    "fedidbSlug": "mastodon",
    "name": "Mastodon",
    "description": "Mastodon is an open source decentralized social network - by the people for the people",
    "descriptionCs": "Otevřená decentralizovaná sociální síť — od lidí pro lidi.",
    "license": "AGPL",
    "website": "https://joinmastodon.org",
    "sourceCode": "https://github.com/mastodon/mastodon",
    "joinUrl": "https://joinmastodon.org/servers",
    "appsUrl": "https://joinmastodon.org/apps",
    "contentType": "microblog",
    "logoUrl": "img/logos/mastodon.png",
    "protocol": "ActivityPub",
    "yearAdded": 2016,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": true,
    "include": true
  },
  {
    "id": "peertube",
    "fedidbSlug": "peertube",
    "name": "PeerTube",
    "description": "Free software to take back control of your videos",
    "descriptionCs": "Svobodný software pro videa pod vlastní kontrolou.",
    "license": "AGPL",
    "website": "https://joinpeertube.org",
    "sourceCode": "https://github.com/Chocobozzz/PeerTube",
    "joinUrl": "https://joinpeertube.org/instances",
    "appsUrl": "https://docs.joinpeertube.org/use/third-party-application",
    "contentType": "video",
    "logoUrl": "img/logos/peertube.png",
    "protocol": "ActivityPub",
    "yearAdded": 2017,
    "centralizedEquivalent": "YouTube",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": true,
    "include": true
  },
  {
    "id": "pleroma",
    "fedidbSlug": "pleroma",
    "name": "Pleroma",
    "description": "Free and Open Federated Microblogging server.",
    "descriptionCs": "Svobodný a otevřený server pro federovaný mikroblog.",
    "license": "AGPL",
    "website": "https://pleroma.social",
    "sourceCode": "https://git.pleroma.social/pleroma/pleroma/",
    "joinUrl": "https://pleroma.social/#featured-instances",
    "appsUrl": "https://docs.pleroma.social/backend/clients",
    "contentType": "microblog",
    "logoUrl": "img/logos/pleroma.png",
    "protocol": "ActivityPub",
    "yearAdded": 2017,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "hubzilla",
    "fedidbSlug": "hubzilla",
    "name": "Hubzilla",
    "description": "Hubzilla is a powerful platform for creating interconnected websites featuring a decentralized identity, communications, and permissions framework built using common webserver technology.",
    "descriptionCs": "Výkonná platforma pro propojené weby s decentralizovanou identitou, komunikací a systémem oprávnění.",
    "license": "MIT",
    "website": "https://hubzilla.org",
    "sourceCode": "https://framagit.org/hubzilla/core",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/hubzilla.png",
    "protocol": "Nomad (Zot) / ActivityPub",
    "yearAdded": 2012,
    "centralizedEquivalent": "Facebook",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "gnusocial",
    "fedidbSlug": "gnusocial",
    "name": "GNU social",
    "description": "The free/libre software social networking platform.",
    "descriptionCs": "Svobodná softwarová platforma pro sociální sítě.",
    "license": "AGPL",
    "website": "https://gnusocial.network",
    "sourceCode": "https://notabug.org/diogo/gnu-social",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/gnusocial.svg",
    "protocol": "OStatus / ActivityPub",
    "yearAdded": 2008,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "plume",
    "fedidbSlug": "plume",
    "name": "Plume",
    "description": "A federated blogging application",
    "descriptionCs": "Federovaná blogovací aplikace.",
    "license": "AGPL",
    "website": "https://joinplu.me",
    "sourceCode": "https://github.com/Plume-org/Plume",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/plume.png",
    "protocol": "ActivityPub",
    "yearAdded": 2018,
    "centralizedEquivalent": "Medium",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "writefreely",
    "fedidbSlug": "writefreely",
    "name": "Writefreely",
    "description": "Minimalist, federated, self-hosted blogging platform.",
    "descriptionCs": "Minimalistická federovaná blogovací platforma pro vlastní provoz.",
    "license": "AGPL",
    "website": "https://writefreely.org",
    "sourceCode": "https://github.com/writeas/writefreely",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/writefreely.png",
    "protocol": "ActivityPub",
    "yearAdded": 2018,
    "centralizedEquivalent": "Medium",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": true,
    "include": true
  },
  {
    "id": "bookwyrm",
    "fedidbSlug": "bookwyrm",
    "name": "Bookwyrm",
    "description": "BookWyrm is a social network for tracking your reading, talking about books, writing reviews, and discovering what to read next.",
    "descriptionCs": "Sociální síť na sledování čtení, recenze knih a tipy, co číst dál.",
    "license": "Anti-Capitalist Software License",
    "website": "https://joinbookwyrm.com",
    "sourceCode": "https://github.com/bookwyrm-social/bookwyrm",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "books",
    "logoUrl": "img/logos/bookwyrm.png",
    "protocol": "ActivityPub",
    "yearAdded": 2020,
    "centralizedEquivalent": "Goodreads",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "wordpress",
    "fedidbSlug": "wordpress",
    "name": "WordPress",
    "description": "Open source software which you can use to easily create a beautiful website, blog, or app.",
    "descriptionCs": "Otevřený software pro snadnou tvorbu webu, blogu nebo aplikace.",
    "license": "GPLv2",
    "website": "https://wordpress.org",
    "sourceCode": "https://github.com/Automattic/wordpress-activitypub",
    "joinUrl": "https://wordpress.org/plugins/activitypub/",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/wordpress.png",
    "protocol": "ActivityPub",
    "yearAdded": 2003,
    "centralizedEquivalent": "WordPress",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": true,
    "include": true
  },
  {
    "id": "misskey",
    "fedidbSlug": "misskey",
    "name": "Misskey",
    "description": "An interplanetary microblogging platform.",
    "descriptionCs": "Mezihvězdná mikroblogovací platforma.",
    "license": "AGPL",
    "website": "https://misskey-hub.net",
    "sourceCode": "https://github.com/misskey-dev/misskey",
    "joinUrl": "https://misskey-hub.net/en/instances.html",
    "appsUrl": "https://misskey-hub.net/en/docs/faq.html#are-there-any-apps-for-ios-android-available",
    "contentType": "microblog",
    "logoUrl": "img/logos/misskey.png",
    "protocol": "ActivityPub",
    "yearAdded": 2014,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "friendica",
    "fedidbSlug": "friendica",
    "name": "Friendica",
    "description": "Friendica is a free and open-source software distributed social network.",
    "descriptionCs": "Svobodná a otevřená distribuovaná sociální síť.",
    "license": "AGPL",
    "website": "https://friendi.ca",
    "sourceCode": "https://github.com/friendica/friendica",
    "joinUrl": "https://friendi.ca/resources/find-a-server/",
    "appsUrl": "https://friendi.ca/resources/mobile-clients/",
    "contentType": "microblog",
    "logoUrl": "img/logos/friendica.png",
    "protocol": "ActivityPub / Diaspora",
    "yearAdded": 2010,
    "centralizedEquivalent": "Facebook",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "activityrelay",
    "fedidbSlug": "activityrelay",
    "name": "Activityrelay",
    "description": "Generic LitePub relay.",
    "descriptionCs": "Obecné LitePub relé.",
    "license": "AGPL",
    "website": "https://git.pleroma.social/pleroma/relay",
    "sourceCode": "https://git.pleroma.social/pleroma/relay",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "REVIEW",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": false
  },
  {
    "id": "lotide",
    "fedidbSlug": "lotide",
    "name": "Lotide",
    "description": "A federated forum / link aggregator using ActivityPub.",
    "descriptionCs": "Federované fórum a agregátor odkazů na ActivityPubu.",
    "license": "AGPL",
    "website": "https://git.sr.ht/~vpzom/lotide",
    "sourceCode": "https://git.sr.ht/~vpzom/lotide",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "forum",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Reddit",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "microblogpub",
    "fedidbSlug": "microblogpub",
    "name": "Microblogpub",
    "description": "A self-hosted, single-user, ActivityPub powered microblog.",
    "descriptionCs": "Self-hosted jednouživatelský mikroblog na ActivityPubu.",
    "license": "AGPL",
    "website": "https://microblog.pub",
    "sourceCode": "https://git.sr.ht/~tsileo/microblog.pub",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "protocol": "ActivityPub",
    "yearAdded": 2018,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "ktistec",
    "fedidbSlug": "ktistec",
    "name": "Ktistec",
    "description": "Single user ActivityPub server.",
    "descriptionCs": "Jednouživatelský ActivityPub server.",
    "license": "AGPL",
    "website": "https://github.com/toddsundsted/ktistec",
    "sourceCode": "https://github.com/toddsundsted/ktistec",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/ktistec.png",
    "protocol": "ActivityPub",
    "yearAdded": 2021,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "drupal",
    "fedidbSlug": "drupal",
    "name": "Drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications",
    "descriptionCs": "Otevřená platforma pro správu obsahu, na níž běží miliony webů a aplikací.",
    "license": "GPL-2.0-or-later",
    "website": "https://www.drupal.org/project/activitypub",
    "sourceCode": "https://git.drupalcode.org/project/activitypub",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/drupal.png",
    "protocol": "ActivityPub",
    "yearAdded": 2001,
    "centralizedEquivalent": "WordPress",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": true,
    "include": true
  },
  {
    "id": "funkwhale",
    "fedidbSlug": "funkwhale",
    "name": "Funkwhale",
    "description": "A social platform to enjoy and share music.",
    "descriptionCs": "Sociální platforma pro poslech a sdílení hudby.",
    "license": "AGPL",
    "website": "https://funkwhale.audio",
    "sourceCode": "https://dev.funkwhale.audio/funkwhale/funkwhale",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "music",
    "logoUrl": "img/logos/funkwhale.svg",
    "protocol": "ActivityPub",
    "yearAdded": 2017,
    "centralizedEquivalent": "Spotify / SoundCloud",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "mobilizon",
    "fedidbSlug": "mobilizon",
    "name": "Mobilizon",
    "description": "Mobilizon is an open source software for event planning and group management.",
    "descriptionCs": "Otevřený software pro plánování událostí a správu skupin.",
    "license": "AGPL",
    "website": "https://joinmobilizon.org",
    "sourceCode": "https://framagit.org/framasoft/mobilizon",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "events",
    "logoUrl": "img/logos/mobilizon.png",
    "protocol": "ActivityPub",
    "yearAdded": 2019,
    "centralizedEquivalent": "Facebook Events",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "gancio",
    "fedidbSlug": "gancio",
    "name": "Gancio",
    "description": "A shared agenda for local communities.",
    "descriptionCs": "Sdílený kalendář pro místní komunity.",
    "license": "AGPL",
    "website": "https://gancio.org",
    "sourceCode": "https://framagit.org/les/gancio",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "events",
    "logoUrl": "img/logos/gancio.png",
    "protocol": "ActivityPub",
    "yearAdded": 2019,
    "centralizedEquivalent": "Facebook Events",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "zap",
    "fedidbSlug": "zap",
    "name": "Zap",
    "description": "A fediverse server.",
    "descriptionCs": "Server pro Fediverse.",
    "license": "Public Domain",
    "website": "https://codeberg.org/zot-archive/zap",
    "sourceCode": "https://codeberg.org/zot-archive/zap",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/zap.png",
    "protocol": "Nomad (Zot) / ActivityPub",
    "yearAdded": 2018,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "smithereen",
    "fedidbSlug": "smithereen",
    "name": "Smithereen",
    "description": "Federated, ActivityPub-compatible social network server with friends, walls, and groups.",
    "descriptionCs": "Federovaný sociální server (ActivityPub) s přáteli, zdmi a skupinami.",
    "license": "Unlicense",
    "website": "https://smithereen.software",
    "sourceCode": "https://github.com/grishka/Smithereen",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/smithereen.png",
    "protocol": "ActivityPub",
    "yearAdded": 2019,
    "centralizedEquivalent": "VKontakte",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "lemmy",
    "fedidbSlug": "lemmy",
    "name": "Lemmy",
    "description": "A link aggregator and forum for the fediverse.",
    "descriptionCs": "Agregátor odkazů a fórum pro Fediverse.",
    "license": "AGPL",
    "website": "https://join-lemmy.org",
    "sourceCode": "https://github.com/LemmyNet/lemmy",
    "joinUrl": "https://join-lemmy.org/instances",
    "appsUrl": "https://join-lemmy.org/apps",
    "contentType": "forum",
    "logoUrl": "img/logos/lemmy.png",
    "protocol": "ActivityPub",
    "yearAdded": 2019,
    "centralizedEquivalent": "Reddit",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "activity-relay",
    "fedidbSlug": "activity-relay",
    "name": "Activity-Relay",
    "description": "Yet another powerful customizable ActivityPub relay server written in Go.",
    "descriptionCs": "Další výkonný a přizpůsobitelný ActivityPub relay server (v Go).",
    "license": "AGPL",
    "website": "https://relay.toot.yukimochi.jp",
    "sourceCode": "https://github.com/yukimochi/Activity-Relay",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "REVIEW",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": false
  },
  {
    "id": "bonfire",
    "fedidbSlug": "bonfire",
    "name": "Bonfire",
    "description": "A federated social network for individuals and communities to design, operate and control their own digital lives.",
    "descriptionCs": "Federovaná síť pro jednotlivce i komunity, aby si navrhli a řídili vlastní digitální život.",
    "license": "AGPL",
    "website": "https://bonfirenetworks.org",
    "sourceCode": "https://github.com/bonfire-networks/bonfire-app",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/bonfire.png",
    "protocol": "ActivityPub",
    "yearAdded": 2020,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "brutalinks",
    "fedidbSlug": "brutalinks",
    "name": "Brutalinks",
    "description": "Link aggregator inspired by reddit using ActivityPub federation.",
    "descriptionCs": "Agregátor odkazů inspirovaný Redditem, federovaný přes ActivityPub.",
    "license": "MIT",
    "website": "https://git.sr.ht/~mariusor/brutalinks",
    "sourceCode": "https://git.sr.ht/~mariusor/brutalinks",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "forum",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Reddit",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "ecko",
    "fedidbSlug": "ecko",
    "name": "Ecko",
    "description": "Ecko is a fork of Mastodon with extra features requested by the community.",
    "descriptionCs": "Fork Mastodonu s funkcemi navíc podle přání komunity.",
    "license": "AGPL",
    "website": "https://magicstone.dev",
    "sourceCode": "https://github.com/magicstone-dev/ecko",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/ecko.svg",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "gotosocial",
    "fedidbSlug": "gotosocial",
    "name": "Gotosocial",
    "description": "GoToSocial is an ActivityPub social network server, written in Golang.",
    "descriptionCs": "Sociální server na ActivityPubu napsaný v Go.",
    "license": "AGPL",
    "website": "https://gotosocial.org",
    "sourceCode": "https://github.com/superseriousbusiness/gotosocial",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/gotosocial.png",
    "protocol": "ActivityPub",
    "yearAdded": 2021,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "hometown",
    "fedidbSlug": "hometown",
    "name": "Hometown",
    "description": "A supported fork of Mastodon that provides local posting and a wider range of content types.",
    "descriptionCs": "Podporovaný fork Mastodonu s lokálním psaním a širší škálou typů obsahu.",
    "license": "AGPL",
    "website": "https://github.com/hometown-fork/hometown",
    "sourceCode": "https://github.com/hometown-fork/hometown",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "protocol": "ActivityPub",
    "yearAdded": 2018,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ano",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "mitra",
    "fedidbSlug": "mitra",
    "name": "Mitra",
    "description": "Federated micro-blogging platform.",
    "descriptionCs": "Federovaná mikroblogovací platforma.",
    "license": "AGPL",
    "website": "https://codeberg.org/silverpill/mitra",
    "sourceCode": "https://codeberg.org/silverpill/mitra",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/mitra.svg",
    "protocol": "ActivityPub",
    "yearAdded": 2021,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "owncast",
    "fedidbSlug": "owncast",
    "name": "Owncast",
    "description": "Owncast is a free and open source live video and web chat server for use with existing popular broadcasting software.",
    "descriptionCs": "Svobodný server pro živé video a webchat k běžnému vysílacímu softwaru.",
    "license": "MIT",
    "website": "https://owncast.online",
    "sourceCode": "https://github.com/owncast/owncast",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "livestream",
    "logoUrl": "img/logos/owncast.png",
    "protocol": "ActivityPub",
    "yearAdded": 2020,
    "centralizedEquivalent": "Twitch",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "akkoma",
    "fedidbSlug": "akkoma",
    "name": "Akkoma",
    "description": "Akkoma is a faster-paced fork, it has a varied and potentially experimental feature set tailored specifically to the corner of the fediverse inhabited by the project creator and contributors.",
    "descriptionCs": "Svižnější fork Pleromy s pestrou a experimentální sadou funkcí.",
    "license": "AGPL",
    "website": "https://akkoma.dev/AkkomaGang/akkoma",
    "sourceCode": "https://akkoma.dev/AkkomaGang/akkoma",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/akkoma.png",
    "protocol": "ActivityPub",
    "yearAdded": 2022,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "bridgy-fed",
    "fedidbSlug": "bridgy-fed",
    "name": "Bridgy-fed",
    "description": "Bridgy Fed connects your web site to Mastodon and the fediverse.",
    "descriptionCs": "Most propojující tvůj web s Mastodonem a Fediverse.",
    "license": "Public domain",
    "website": "https://fed.brid.gy",
    "sourceCode": "https://github.com/snarfed/bridgy-fed",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "REVIEW",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": false
  },
  {
    "id": "cherrypick",
    "fedidbSlug": "cherrypick",
    "name": "Cherrypick",
    "description": "Fork of Misskey.",
    "descriptionCs": "Fork Misskey.",
    "license": "AGPL",
    "website": "https://github.com/kokonect-link/cherrypick",
    "sourceCode": "https://github.com/kokonect-link/cherrypick",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/cherrypick.png",
    "protocol": "ActivityPub",
    "yearAdded": 2021,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "fedibird",
    "fedidbSlug": "fedibird",
    "name": "Fedibird",
    "description": "Fedibird is a fork of Mastodon arranged with features maintained by Takeshi Umeda (noellabo).",
    "descriptionCs": "Fork Mastodonu s funkcemi od Takeshiho Umedy (noellabo).",
    "license": "AGPL",
    "website": "https://github.com/fedibird/mastodon",
    "sourceCode": "https://github.com/fedibird/mastodon",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/fedibird.png",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "foundkey",
    "fedidbSlug": "foundkey",
    "name": "Foundkey",
    "description": "Forked from Misskey, FoundKey improves on maintainability and behaviour, while also bringing in useful features.",
    "descriptionCs": "Fork Misskey se zaměřením na udržovatelnost a užitečné funkce navíc.",
    "license": "AGPL",
    "website": "https://akkoma.dev/FoundKeyGang/FoundKey",
    "sourceCode": "https://akkoma.dev/FoundKeyGang/FoundKey",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/foundkey.svg",
    "protocol": "ActivityPub",
    "yearAdded": 2022,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "meisskey",
    "fedidbSlug": "meisskey",
    "name": "Meisskey",
    "description": "Meisskey is a decentralized microblogging platform, a fork of Misskey.",
    "descriptionCs": "Decentralizovaná mikroblogovací platforma, fork Misskey.",
    "license": "AGPL",
    "website": "https://github.com/mei23/misskey",
    "sourceCode": "https://github.com/mei23/misskey",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "microdotblog",
    "fedidbSlug": "microdotblog",
    "name": "Microdotblog",
    "description": "Personal blogging that makes it easy to be social.",
    "descriptionCs": "Osobní blogování, se kterým je snadné být společenský.",
    "license": "",
    "website": "https://micro.blog",
    "sourceCode": "",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/microdotblog.png",
    "protocol": "ActivityPub",
    "yearAdded": 2017,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "snac",
    "fedidbSlug": "snac",
    "name": "Snac",
    "description": "A simple, minimalistic ActivityPub instance written in portable C.",
    "descriptionCs": "Jednoduchá a minimalistická ActivityPub instance napsaná v přenositelném C.",
    "license": "MIT",
    "website": "https://codeberg.org/grunfink/snac2",
    "sourceCode": "https://codeberg.org/grunfink/snac2",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/snac.png",
    "protocol": "ActivityPub",
    "yearAdded": 2022,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "stegodon",
    "fedidbSlug": "stegodon",
    "name": "stegodon",
    "description": "SSH-first federated blogging platform. Users connect via SSH to create notes in a terminal interface that federate to the Fediverse via ActivityPub.",
    "descriptionCs": "Blogovací platforma „SSH na prvním místě“ — poznámky píšeš v terminálu přes SSH a federují se přes ActivityPub.",
    "license": "MIT",
    "website": "https://stegodon.social",
    "sourceCode": "https://github.com/deemkeen/stegodon",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/stegodon.png",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "experimentalni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "takahe",
    "fedidbSlug": "takahe",
    "name": "Takahe",
    "description": "An efficient ActivityPub Server, for small installs with multiple domains.",
    "descriptionCs": "Efektivní ActivityPub server pro malé instalace s více doménami.",
    "license": "BSD-3",
    "website": "https://jointakahe.org",
    "sourceCode": "https://github.com/jointakahe/takahe",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/takahe.png",
    "protocol": "ActivityPub",
    "yearAdded": 2022,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "firefish",
    "fedidbSlug": "firefish",
    "name": "Firefish",
    "description": "A fun, new, open way to experience social media.",
    "descriptionCs": "Zábavný a otevřený nový způsob, jak zažít sociální sítě.",
    "license": "AGPL",
    "website": "",
    "sourceCode": "",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/firefish.png",
    "protocol": "ActivityPub",
    "yearAdded": 2022,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "castecne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "mbin",
    "fedidbSlug": "mbin",
    "name": "Mbin",
    "description": "Mbin a fork of kbin, community-focused.",
    "descriptionCs": "Fork kbinu se zaměřením na komunitu.",
    "license": "AGPL",
    "website": "https://joinmbin.org/",
    "sourceCode": "https://github.com/MbinOrg/mbin",
    "joinUrl": "https://joinmbin.org/",
    "appsUrl": "https://joinmbin.org/apps/",
    "contentType": "forum",
    "logoUrl": "img/logos/mbin.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Reddit",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "iceshrimp",
    "fedidbSlug": "iceshrimp",
    "name": "Iceshrimp",
    "description": "YAMF (Yet another Misskey fork) bringing you no-nonsense fixes, features & improvements you actually want since 2023",
    "descriptionCs": "Další fork Misskey — věcné opravy, funkce a vylepšení, která reálně chceš.",
    "license": "AGPL",
    "website": "https://iceshrimp.dev/iceshrimp/iceshrimp",
    "sourceCode": "https://iceshrimp.dev/iceshrimp/iceshrimp",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/iceshrimp.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "castecne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "sharkey",
    "fedidbSlug": "sharkey",
    "name": "Sharkey",
    "description": "Sharkey is an Misskey fork following upstream changes when possible, with added features.",
    "descriptionCs": "Fork Misskey, který sleduje upstream a přidává funkce navíc.",
    "license": "AGPL",
    "website": "https://joinsharkey.org",
    "sourceCode": "https://activitypub.software/TransFem-org/Sharkey",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/sharkey.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "postmarks",
    "fedidbSlug": "postmarks",
    "name": "Postmarks",
    "description": "Single-user bookmarking website designed to live on the Fediverse.",
    "descriptionCs": "Jednouživatelský web na záložky žijící ve Fediverse.",
    "license": "MIT",
    "website": "https://postmarks.glitch.me",
    "sourceCode": "https://github.com/ckolderup/postmarks",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "links",
    "logoUrl": "img/logos/postmarks.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Pocket / Pinboard",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "piefed",
    "fedidbSlug": "piefed",
    "name": "Piefed",
    "description": "An open source reddit-like federated forum that works well with Lemmy and others.",
    "descriptionCs": "Otevřené reddit-like federované fórum, které ladí s Lemmy a dalšími.",
    "license": "AGPL",
    "website": "https://join.piefed.social",
    "sourceCode": "https://codeberg.org/rimu/pyfedi",
    "joinUrl": "https://join.piefed.social/try/",
    "appsUrl": "",
    "contentType": "forum",
    "logoUrl": "img/logos/piefed.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Reddit",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "ghost",
    "fedidbSlug": "ghost",
    "name": "Ghost",
    "description": "Ghost is a powerful app for professional publishers to create, share, and grow a business around their content.",
    "descriptionCs": "Výkonný nástroj pro profesionální vydavatele — tvorba, sdílení a byznys kolem obsahu.",
    "license": "MIT",
    "website": "https://ghost.org",
    "sourceCode": "https://github.com/TryGhost/Ghost",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/ghost.png",
    "protocol": "ActivityPub",
    "yearAdded": 2013,
    "centralizedEquivalent": "Medium / Substack",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": true,
    "include": true
  },
  {
    "id": "hollo",
    "fedidbSlug": "hollo",
    "name": "Hollo",
    "description": "Hollo is a federated single-user microblogging software powered by Fedify.",
    "descriptionCs": "Federovaný jednouživatelský mikroblog postavený na Fedify.",
    "license": "AGPL",
    "website": "https://docs.hollo.social",
    "sourceCode": "https://github.com/fedify-dev/hollo",
    "joinUrl": "",
    "appsUrl": "https://docs.hollo.social/clients/",
    "contentType": "microblog",
    "logoUrl": "img/logos/hollo.svg",
    "protocol": "ActivityPub",
    "yearAdded": 2024,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "kmyblue",
    "fedidbSlug": "kmyblue",
    "name": "Kmyblue",
    "description": "Mastodon, which specializes in small communities for the inner circle.",
    "descriptionCs": "Mastodon zaměřený na malé komunity nejbližšího okruhu.",
    "license": "AGPL",
    "website": "https://github.com/kmycode/mastodon",
    "sourceCode": "https://github.com/kmycode/mastodon",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/kmyblue.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "loops",
    "fedidbSlug": "loops",
    "name": "Loops",
    "description": "The federated short video sharing platform. Share, discover, and create short videos across the social web.",
    "descriptionCs": "Federovaná platforma na krátká videa — sdílej, objevuj a tvoř napříč sociálním webem.",
    "license": "AGPL",
    "website": "https://joinloops.org",
    "sourceCode": "https://github.com/joinloops/loops-server",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "shortvideo",
    "logoUrl": "img/logos/loops.png",
    "protocol": "ActivityPub",
    "yearAdded": 2024,
    "centralizedEquivalent": "TikTok",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "wafrn",
    "fedidbSlug": "wafrn",
    "name": "wafrn",
    "description": "Wafrn is a federated social media inspired by tumblr.",
    "descriptionCs": "Federovaná sociální síť inspirovaná Tumblrem.",
    "license": "AGPL",
    "website": "https://wafrn.net",
    "sourceCode": "https://codeberg.org/wafrn/wafrn",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/wafrn.png",
    "protocol": "ActivityPub",
    "yearAdded": 2023,
    "centralizedEquivalent": "Tumblr",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "emissary",
    "fedidbSlug": "emissary",
    "name": "Emissary",
    "description": "The Social Web Toolkit: AProgrammable server for custom Fediverse apps.",
    "descriptionCs": "Sada nástrojů pro sociální web — programovatelný server pro vlastní Fediverse aplikace.",
    "license": "AGPL",
    "website": "https://emissary.dev",
    "sourceCode": "https://github.com/EmissarySocial/emissary",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "blog",
    "logoUrl": "img/logos/emissary.png",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Medium",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "neodb",
    "fedidbSlug": "neodb",
    "name": "NeoDB",
    "description": "Review and share books, movies, music, games, and more",
    "descriptionCs": "Recenzuj a sdílej knihy, filmy, hudbu, hry a další.",
    "license": "AGPL",
    "website": "https://neodb.net",
    "sourceCode": "https://github.com/neodb-social/neodb",
    "joinUrl": "https://neodb.net/servers/",
    "appsUrl": "https://neodb.net/apps/",
    "contentType": "books",
    "logoUrl": "img/logos/neodb.png",
    "protocol": "ActivityPub",
    "yearAdded": 2021,
    "centralizedEquivalent": "Goodreads / Letterboxd",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "nodebb",
    "fedidbSlug": "nodebb",
    "name": "NodeBB",
    "description": "A better community platform for the modern web",
    "descriptionCs": "Lepší komunitní platforma pro moderní web.",
    "license": "GPL-3.0",
    "website": "https://nodebb.org",
    "sourceCode": "https://github.com/NodeBB/NodeBB",
    "joinUrl": "",
    "appsUrl": "https://nodebb.org",
    "contentType": "forum",
    "logoUrl": "img/logos/nodebb.png",
    "protocol": "ActivityPub",
    "yearAdded": 2013,
    "centralizedEquivalent": "Discourse",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "irwin",
    "fedidbSlug": "irwin",
    "name": "irwin",
    "description": "an activitypub and indieauth server",
    "descriptionCs": "ActivityPub a IndieAuth server.",
    "license": "MIT",
    "website": "https://otisburg.social",
    "sourceCode": "https://github.com/herestomwiththeweather/irwin",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "REVIEW",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "",
    "czechUI": "ne",
    "devStatus": "experimentalni",
    "managedHosting": false,
    "include": false
  },
  {
    "id": "vernissage",
    "fedidbSlug": "vernissage",
    "name": "Vernissage",
    "description": "Vernissage is a free platform designed for photographers. It's ad-free and focused on community and creativity, not algorithms.",
    "descriptionCs": "Svobodná platforma pro fotografy — bez reklam a algoritmů, s důrazem na komunitu a tvořivost.",
    "license": "Apache 2.0",
    "website": "https://vernissage.photos/home",
    "sourceCode": "https://github.com/VernissageApp/VernissageServer",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "photos",
    "logoUrl": "img/logos/vernissage.png",
    "protocol": "ActivityPub",
    "yearAdded": 2024,
    "centralizedEquivalent": "Instagram",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "betula",
    "fedidbSlug": "betula",
    "name": "Betula",
    "description": "Single-user federated bookmark manager with hypertext descriptions, tagging, local and federated search, archival and whatnot.",
    "descriptionCs": "Jednouživatelský federovaný správce záložek s hypertextovými popisy, tagy a vyhledáváním.",
    "license": "AGPL",
    "website": "https://betula.mycorrhiza.wiki",
    "sourceCode": "https://codeberg.org/bouncepaw/betula",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "links",
    "logoUrl": "img/logos/betula.svg",
    "protocol": "ActivityPub",
    "yearAdded": 2022,
    "centralizedEquivalent": "Pocket / Pinboard",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "hackerspub",
    "fedidbSlug": "hackerspub",
    "name": "Hackers' Pub",
    "description": "ActivityPub-enabled social network for hackers.",
    "descriptionCs": "Sociální síť s ActivityPubem pro hackery.",
    "license": "AGPL",
    "website": "https://hackers.pub/",
    "sourceCode": "https://github.com/hackers-pub/hackerspub",
    "joinUrl": "https://hackers.pub/sign",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/hackerspub.png",
    "protocol": "ActivityPub",
    "yearAdded": 2024,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "frequency",
    "fedidbSlug": "frequency",
    "name": "frequency",
    "description": "A mindful, federated social network to share your life with family and friends",
    "descriptionCs": "Vědomá federovaná síť pro sdílení života s rodinou a přáteli.",
    "license": "",
    "website": "https://frequency.app",
    "sourceCode": "https://github.com/jesseplusplus/decodon",
    "joinUrl": "",
    "appsUrl": "https://apps.apple.com/us/app/frequency-social/id1522993423",
    "contentType": "photos",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": false
  },
  {
    "id": "appy",
    "fedidbSlug": "appy",
    "name": "appy",
    "description": "A lightweight server implementing the ActivityPub protocol in Python over fastAPI.",
    "descriptionCs": "Lehký server implementující ActivityPub v Pythonu nad FastAPI.",
    "license": "GNU GENERAL PUBLIC LICENSE, Version 3",
    "website": "https://appy.cat",
    "sourceCode": "https://codeberg.org/spla/appy",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/appy.png",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "Twitter / X",
    "czechUI": "ne",
    "devStatus": "experimentalni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "socialhome",
    "fedidbSlug": "socialhome",
    "name": "Socialhome",
    "description": "Federated personal profile with rich content.",
    "descriptionCs": "Federovaný osobní profil s bohatým obsahem.",
    "license": "AGPL",
    "website": "https://socialhome.network",
    "sourceCode": "https://codeberg.org/socialhome",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "logoUrl": "img/logos/socialhome.png",
    "protocol": "ActivityPub",
    "yearAdded": 2017,
    "centralizedEquivalent": "Facebook",
    "czechUI": "ne",
    "devStatus": "utlumeny",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "castopod",
    "fedidbSlug": "castopod",
    "name": "Castopod",
    "description": "The free and open-source solution to your podcasting 2.0 journey.",
    "descriptionCs": "Svobodné a otevřené řešení pro tvůj podcasting 2.0.",
    "license": "AGPL",
    "website": "https://castopod.org",
    "sourceCode": "https://code.castopod.org/adaures/castopod",
    "joinUrl": "https://index.castopod.org",
    "appsUrl": "",
    "contentType": "podcast",
    "logoUrl": "img/logos/castopod.svg",
    "protocol": "ActivityPub",
    "yearAdded": 2020,
    "centralizedEquivalent": "Spotify (podcasty)",
    "czechUI": "ne",
    "devStatus": "aktivni",
    "managedHosting": false,
    "include": true
  },
  {
    "id": "murlog",
    "fedidbSlug": "murlog",
    "name": "murlog",
    "description": "A single-user ActivityPub microblog server.",
    "descriptionCs": "Jednouživatelský ActivityPub mikroblog server.",
    "license": "AGPL",
    "website": "https://murlog.org",
    "sourceCode": "https://github.com/murlog-org/murlog",
    "joinUrl": "",
    "appsUrl": "",
    "contentType": "microblog",
    "protocol": "ActivityPub",
    "yearAdded": null,
    "centralizedEquivalent": "",
    "czechUI": "ne",
    "devStatus": "experimentalni",
    "managedHosting": false,
    "include": false
  }
];
