/* Globální doporučené servery pro Pohled 3 „Instance" — varianta B (ručně udržovaný
   seznam, nulová externí závislost, plná kontrola). RUČNĚ EDITOVATELNÝ.

   Schéma = typ Instance (viz web/app.js adaptér). Klíčová pole:
     appId      → musí odpovídat App.id z web/apps.js (Pohled 2)
     region     → vždy "global" (CZ/SK jdou ze Sloníka přes symlink)
     focus      → taxonomie: obecna|tech|umeni|akademicka|hry|region|lgbtq
     registration → open|approval|invite|closed (best-effort; živě by dorovnal NodeInfo job)
     beginnerFriendly → prověřenost (ne velikost)

   POZN.: registration a users se u veřejných serverů mění — ber jako kurátorský
   výchozí stav (žádný job je nedorovnává, bin/refresh_instance_stats.rb nikdy nevznikl).
   Poslední ruční kontrola: 25. 9. 2026 přes API (Mastodon /api/v2/instance, Lemmy
   /api/v3/site, Pixelfed /api/v1/instance, PieFed nodeinfo) — 12 z 18 záznamů bylo
   zastaralých; skoro všude se schvaluje nebo zve (obrana proti botům). U pozvánek
   (mas.to, fosstodon.org, mastodon.online) účet dostaneš jen přes stávajícího
   uživatele → beginnerFriendly false; zavřené (scholar.social, pixey.org) zůstávají
   v katalogu se štítkem, průvodce je sám vynechá. users = celkový počet účtů z API.
   Ghost, Owncast a Castopod tu záměrně nejsou: nemají veřejné instance s registrací
   (self-hosting nebo placený hosting) → průvodce je vede na oficiální stránku. */
window.FEDIK_INSTANCES_MANUAL = [
  // ── Mastodon ──
  { id: "mastodon.social",  domain: "mastodon.social",  name: "mastodon.social",  appId: "mastodon", region: "global", focus: ["obecna"], registration: "open", beginnerFriendly: true,  users: 3409641, source: "manual", signupUrl: "https://mastodon.social/auth/sign_up", description: "Vlajkový server projektu Mastodon.", descriptionEn: "The flagship Mastodon server." },
  { id: "mastodon.online",  domain: "mastodon.online",  name: "mastodon.online",  appId: "mastodon", region: "global", focus: ["obecna"], registration: "invite",     beginnerFriendly: false, users: 188285, source: "manual", signupUrl: "https://mastodon.online/auth/sign_up", description: "Obecný server provozovaný týmem Mastodonu.", descriptionEn: "A general server run by the Mastodon team." },
  { id: "mas.to",           domain: "mas.to",           name: "mas.to",           appId: "mastodon", region: "global", focus: ["obecna"], registration: "invite",     beginnerFriendly: false, users: 188060, source: "manual", signupUrl: "https://mas.to/auth/sign_up", description: "Velký přátelský obecný server.", descriptionEn: "A large, friendly general server." },
  { id: "mstdn.social",     domain: "mstdn.social",     name: "mstdn.social",     appId: "mastodon", region: "global", focus: ["obecna"], registration: "approval",     beginnerFriendly: true,  users: 276761, source: "manual", signupUrl: "https://mstdn.social/auth/sign_up", description: "Obecný server pro širokou veřejnost.", descriptionEn: "A general server for the wider public." },
  { id: "mastodon.world",   domain: "mastodon.world",   name: "mastodon.world",   appId: "mastodon", region: "global", focus: ["obecna"], registration: "approval",     beginnerFriendly: true,  users: 196880, source: "manual", signupUrl: "https://mastodon.world/auth/sign_up", description: "Obecný mezinárodní server.", descriptionEn: "A general international server." },
  { id: "fosstodon.org",    domain: "fosstodon.org",    name: "Fosstodon",        appId: "mastodon", region: "global", focus: ["tech"],   registration: "invite", beginnerFriendly: false, users: 62708, source: "manual", signupUrl: "https://fosstodon.org/auth/sign_up", description: "Komunita kolem open source a technologií.", descriptionEn: "A community around open source and technology." },
  { id: "hachyderm.io",     domain: "hachyderm.io",     name: "Hachyderm",        appId: "mastodon", region: "global", focus: ["tech"],   registration: "approval", beginnerFriendly: true,  users: 57903, source: "manual", signupUrl: "https://hachyderm.io/auth/sign_up", description: "Server pro IT profesionály a kurátorovaný provoz.", descriptionEn: "A curated server for IT professionals." },
  { id: "infosec.exchange", domain: "infosec.exchange", name: "infosec.exchange", appId: "mastodon", region: "global", focus: ["tech"],   registration: "approval", beginnerFriendly: false, users: 83344, source: "manual", signupUrl: "https://infosec.exchange/auth/sign_up", description: "Komunita kolem kybernetické bezpečnosti.", descriptionEn: "A community around cybersecurity." },
  { id: "mastodon.art",     domain: "mastodon.art",     name: "mastodon.art",     appId: "mastodon", region: "global", focus: ["umeni"],  registration: "approval", beginnerFriendly: true,  users: 42343, source: "manual", signupUrl: "https://mastodon.art/auth/sign_up", description: "Server pro výtvarníky a tvůrce.", descriptionEn: "A server for artists and creators." },
  { id: "scholar.social",   domain: "scholar.social",   name: "scholar.social",   appId: "mastodon", region: "global", focus: ["akademicka"], registration: "closed", beginnerFriendly: false, users: 1227, source: "manual", signupUrl: "https://scholar.social/auth/sign_up", description: "Akademická komunita (věda, výzkum, výuka).", descriptionEn: "An academic community (science, research, teaching)." },
  { id: "dice.camp",        domain: "dice.camp",        name: "dice.camp",        appId: "mastodon", region: "global", focus: ["hry"],    registration: "approval", beginnerFriendly: false, users: 9921, source: "manual", signupUrl: "https://dice.camp/auth/sign_up", description: "Komunita kolem deskových a stolních her.", descriptionEn: "A community around tabletop and board games." },
  { id: "tech.lgbt",        domain: "tech.lgbt",        name: "tech.lgbt",        appId: "mastodon", region: "global", focus: ["lgbtq", "tech"], registration: "approval", beginnerFriendly: true,  users: 15903, source: "manual", signupUrl: "https://tech.lgbt/auth/sign_up", description: "Přátelský server pro LGBTQ+ komunitu v IT.", descriptionEn: "A friendly server for the LGBTQ+ community in tech." },
  // ── Pixelfed (fotky) ──
  { id: "pixelfed.social",  domain: "pixelfed.social",  name: "pixelfed.social",  appId: "pixelfed", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  users: 585586, source: "manual", signupUrl: "https://pixelfed.social/register", description: "Vlajkový server Pixelfedu (sdílení fotek).", descriptionEn: "The flagship Pixelfed server (photo sharing)." },
  { id: "pixey.org",        domain: "pixey.org",        name: "Pixey",            appId: "pixelfed", region: "global", focus: ["obecna"], registration: "closed",     beginnerFriendly: false, users: 13190, source: "manual", signupUrl: "https://pixey.org/register", description: "Oblíbený obecný Pixelfed server.", descriptionEn: "A popular general Pixelfed server." },
  // ── Lemmy (fórum) ──
  { id: "lemmy.world",      domain: "lemmy.world",      name: "Lemmy.World",      appId: "lemmy",    region: "global", focus: ["obecna"], registration: "approval",     beginnerFriendly: true,  users: 198757, source: "manual", signupUrl: "https://lemmy.world/signup", description: "Největší obecná Lemmy instance.", descriptionEn: "The largest general Lemmy instance." },
  { id: "lemmy.ml",         domain: "lemmy.ml",         name: "lemmy.ml",         appId: "lemmy",    region: "global", focus: ["obecna"], registration: "approval",     beginnerFriendly: false, users: 58728, source: "manual", signupUrl: "https://lemmy.ml/signup", description: "Domovská instance projektu Lemmy.", descriptionEn: "The home instance of the Lemmy project." },
  { id: "sh.itjust.works",  domain: "sh.itjust.works",  name: "sh.itjust.works",  appId: "lemmy",    region: "global", focus: ["obecna"], registration: "approval",     beginnerFriendly: true,  users: 35080, source: "manual", signupUrl: "https://sh.itjust.works/signup", description: "Velká obecná Lemmy instance.", descriptionEn: "A large general Lemmy instance." },
  { id: "piefed.social",    domain: "piefed.social",    name: "PieFed",           appId: "piefed",   region: "global", focus: ["obecna"], registration: "open", beginnerFriendly: true,  users: 6802, source: "manual", signupUrl: "https://piefed.social/auth/register", description: "Vlajkový PieFed (alternativa k Redditu).", descriptionEn: "The flagship PieFed (a Reddit alternative)." },
  // ── Mbin (fórum, kbin-fork) ── ověřeno 25. 9. 2026 (nodeinfo + registrační stránka)
  { id: "fedia.io",         domain: "fedia.io",         name: "Fedia",            appId: "mbin",     region: "global", focus: ["obecna"], registration: "approval", beginnerFriendly: true,  users: 6542, source: "manual", signupUrl: "https://fedia.io/register", description: "Největší Mbin instance; ve formuláři napíšeš, proč se chceš přidat.", descriptionEn: "The largest Mbin instance; the form asks why you want to join." },
  { id: "kbin.earth",       domain: "kbin.earth",       name: "kbin.earth",       appId: "mbin",     region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  users: 905, source: "manual", signupUrl: "https://kbin.earth/register", description: "Menší obecná Mbin instance s otevřenou registrací.", descriptionEn: "A smaller general Mbin instance with open registration." },
  // ── Loops (krátká videa) ── jediná veřejná instance projektu; účet se zakládá v mobilní appce
  { id: "loops.video",      domain: "loops.video",      name: "Loops",            appId: "loops",    region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  users: 45978, source: "manual", signupUrl: "https://loops.video/", description: "Vlajková (a zatím jediná veřejná) instance Loops. Účet založíš v mobilní aplikaci pro iOS/Android.", descriptionEn: "The flagship (and so far only public) Loops instance. You sign up in the iOS/Android app." },
  // ── BookWyrm (knihy) ── web má ochranu proti botům (Anubis), pro lidi funguje normálně
  { id: "bookwyrm.social",  domain: "bookwyrm.social",  name: "bookwyrm.social",  appId: "bookwyrm", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  users: 29812, source: "manual", signupUrl: "https://bookwyrm.social/", description: "Vlajková instance BookWyrm (čtenářský deník, recenze, sdílení knih).", descriptionEn: "The flagship BookWyrm instance (reading log, reviews, sharing books)." },
  { id: "wyrms.de",         domain: "wyrms.de",         name: "wyrms.de",         appId: "bookwyrm", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  users: 489, source: "manual", signupUrl: "https://wyrms.de/", description: "Menší evropská (německá) instance BookWyrm.", descriptionEn: "A smaller European (German) BookWyrm instance." },
  // ── Funkwhale (hudba) ──
  { id: "open.audio",       domain: "open.audio",       name: "Open Audio",       appId: "funkwhale", region: "global", focus: ["obecna"], registration: "open",    beginnerFriendly: true,  users: 5089, source: "manual", signupUrl: "https://open.audio/signup", description: "Největší veřejná Funkwhale instance (hudba pod svobodnými licencemi).", descriptionEn: "The largest public Funkwhale instance (freely licensed music)." },
  { id: "funkwhale.it",     domain: "funkwhale.it",     name: "funkwhale.it",     appId: "funkwhale", region: "global", focus: ["obecna"], registration: "open",    beginnerFriendly: true,  users: 1814, source: "manual", signupUrl: "https://funkwhale.it/signup", description: "Italská obecná Funkwhale instance s otevřenou registrací.", descriptionEn: "An Italian general Funkwhale instance with open registration." },
  // ── Mobilizon (události) ──
  { id: "mobilizon.fr",     domain: "mobilizon.fr",     name: "Mobilizon.fr",     appId: "mobilizon", region: "global", focus: ["obecna"], registration: "open",    beginnerFriendly: true,  users: 15392, source: "manual", signupUrl: "https://mobilizon.fr/register/user", description: "Instance provozovaná Framasoftem, autory Mobilizonu; největší veřejná.", descriptionEn: "Run by Framasoft, the makers of Mobilizon; the largest public instance." },
  { id: "mobilizon.chapril.org", domain: "mobilizon.chapril.org", name: "Mobilizon Chapril", appId: "mobilizon", region: "global", focus: ["obecna"], registration: "open", beginnerFriendly: true, users: 1218, source: "manual", signupUrl: "https://mobilizon.chapril.org/register/user", description: "Instance francouzského spolku April (svobodný software).", descriptionEn: "Run by April, the French free-software association." },
  // ── WriteFreely (blog) ── qua.name a wordsmith.social mají registraci zavřenou (25. 9. 2026)
  { id: "text.tchncs.de",   domain: "text.tchncs.de",   name: "tchncs Reader",    appId: "writefreely", region: "global", focus: ["obecna"], registration: "open",  beginnerFriendly: true,  users: 1201, source: "manual", signupUrl: "https://text.tchncs.de/signup", description: "WriteFreely instance dlouholetého německého provozovatele tchncs.de.", descriptionEn: "WriteFreely instance by the long-running German host tchncs.de." },
  { id: "write.as",         domain: "write.as",         name: "Write.as",         appId: "writefreely", region: "global", focus: ["obecna"], registration: "open",  beginnerFriendly: true,  source: "manual", signupUrl: "https://write.as/signup", description: "Hostovaná služba autorů WriteFreely; základní účet zdarma, víc blogů za poplatek.", descriptionEn: "Hosted service by the WriteFreely authors; basic account free, more blogs paid." },
];
