/* Globální doporučené servery pro Pohled 3 „Instance" — varianta B (ručně udržovaný
   seznam, nulová externí závislost, plná kontrola). RUČNĚ EDITOVATELNÝ.

   Schéma = typ Instance (viz web/app.js adaptér). Klíčová pole:
     appId      → musí odpovídat App.id z web/apps.js (Pohled 2)
     region     → vždy "global" (CZ/SK jdou ze Sloníka přes symlink)
     focus      → taxonomie: obecna|tech|umeni|akademicka|hry|region|lgbtq
     registration → open|approval|invite|closed (best-effort; živě by dorovnal NodeInfo job)
     beginnerFriendly → prověřenost (ne velikost)

   POZN.: registration a users se u veřejných serverů mění — ber jako kurátorský
   výchozí stav; volitelná NodeInfo vrstva (bin/refresh_instance_stats.rb) je drží svěží. */
window.FEDIK_INSTANCES_MANUAL = [
  // ── Mastodon ──
  { id: "mastodon.social",  domain: "mastodon.social",  name: "mastodon.social",  appId: "mastodon", region: "global", focus: ["obecna"], registration: "approval", beginnerFriendly: true,  source: "manual", signupUrl: "https://mastodon.social/auth/sign_up", description: "Vlajkový server projektu Mastodon.", descriptionEn: "The flagship Mastodon server." },
  { id: "mastodon.online",  domain: "mastodon.online",  name: "mastodon.online",  appId: "mastodon", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://mastodon.online/auth/sign_up", description: "Obecný server provozovaný týmem Mastodonu.", descriptionEn: "A general server run by the Mastodon team." },
  { id: "mas.to",           domain: "mas.to",           name: "mas.to",           appId: "mastodon", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://mas.to/auth/sign_up", description: "Velký přátelský obecný server.", descriptionEn: "A large, friendly general server." },
  { id: "mstdn.social",     domain: "mstdn.social",     name: "mstdn.social",     appId: "mastodon", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://mstdn.social/auth/sign_up", description: "Obecný server pro širokou veřejnost.", descriptionEn: "A general server for the wider public." },
  { id: "mastodon.world",   domain: "mastodon.world",   name: "mastodon.world",   appId: "mastodon", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://mastodon.world/auth/sign_up", description: "Obecný mezinárodní server.", descriptionEn: "A general international server." },
  { id: "fosstodon.org",    domain: "fosstodon.org",    name: "Fosstodon",        appId: "mastodon", region: "global", focus: ["tech"],   registration: "approval", beginnerFriendly: true,  source: "manual", signupUrl: "https://fosstodon.org/auth/sign_up", description: "Komunita kolem open source a technologií.", descriptionEn: "A community around open source and technology." },
  { id: "hachyderm.io",     domain: "hachyderm.io",     name: "Hachyderm",        appId: "mastodon", region: "global", focus: ["tech"],   registration: "approval", beginnerFriendly: true,  source: "manual", signupUrl: "https://hachyderm.io/auth/sign_up", description: "Server pro IT profesionály a kurátorovaný provoz.", descriptionEn: "A curated server for IT professionals." },
  { id: "infosec.exchange", domain: "infosec.exchange", name: "infosec.exchange", appId: "mastodon", region: "global", focus: ["tech"],   registration: "approval", beginnerFriendly: false, source: "manual", signupUrl: "https://infosec.exchange/auth/sign_up", description: "Komunita kolem kybernetické bezpečnosti.", descriptionEn: "A community around cybersecurity." },
  { id: "mastodon.art",     domain: "mastodon.art",     name: "mastodon.art",     appId: "mastodon", region: "global", focus: ["umeni"],  registration: "approval", beginnerFriendly: true,  source: "manual", signupUrl: "https://mastodon.art/auth/sign_up", description: "Server pro výtvarníky a tvůrce.", descriptionEn: "A server for artists and creators." },
  { id: "scholar.social",   domain: "scholar.social",   name: "scholar.social",   appId: "mastodon", region: "global", focus: ["akademicka"], registration: "approval", beginnerFriendly: true, source: "manual", signupUrl: "https://scholar.social/auth/sign_up", description: "Akademická komunita (věda, výzkum, výuka).", descriptionEn: "An academic community (science, research, teaching)." },
  { id: "dice.camp",        domain: "dice.camp",        name: "dice.camp",        appId: "mastodon", region: "global", focus: ["hry"],    registration: "approval", beginnerFriendly: false, source: "manual", signupUrl: "https://dice.camp/auth/sign_up", description: "Komunita kolem deskových a stolních her.", descriptionEn: "A community around tabletop and board games." },
  { id: "tech.lgbt",        domain: "tech.lgbt",        name: "tech.lgbt",        appId: "mastodon", region: "global", focus: ["lgbtq", "tech"], registration: "approval", beginnerFriendly: true, source: "manual", signupUrl: "https://tech.lgbt/auth/sign_up", description: "Přátelský server pro LGBTQ+ komunitu v IT.", descriptionEn: "A friendly server for the LGBTQ+ community in tech." },
  // ── Pixelfed (fotky) ──
  { id: "pixelfed.social",  domain: "pixelfed.social",  name: "pixelfed.social",  appId: "pixelfed", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://pixelfed.social/register", description: "Vlajkový server Pixelfedu (sdílení fotek).", descriptionEn: "The flagship Pixelfed server (photo sharing)." },
  { id: "pixey.org",        domain: "pixey.org",        name: "Pixey",            appId: "pixelfed", region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://pixey.org/register", description: "Oblíbený obecný Pixelfed server.", descriptionEn: "A popular general Pixelfed server." },
  // ── Lemmy (fórum) ──
  { id: "lemmy.world",      domain: "lemmy.world",      name: "Lemmy.World",      appId: "lemmy",    region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://lemmy.world/signup", description: "Největší obecná Lemmy instance.", descriptionEn: "The largest general Lemmy instance." },
  { id: "lemmy.ml",         domain: "lemmy.ml",         name: "lemmy.ml",         appId: "lemmy",    region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: false, source: "manual", signupUrl: "https://lemmy.ml/signup", description: "Domovská instance projektu Lemmy.", descriptionEn: "The home instance of the Lemmy project." },
  { id: "sh.itjust.works",  domain: "sh.itjust.works",  name: "sh.itjust.works",  appId: "lemmy",    region: "global", focus: ["obecna"], registration: "open",     beginnerFriendly: true,  source: "manual", signupUrl: "https://sh.itjust.works/signup", description: "Velká obecná Lemmy instance.", descriptionEn: "A large general Lemmy instance." },
  { id: "piefed.social",    domain: "piefed.social",    name: "PieFed",           appId: "piefed",   region: "global", focus: ["obecna"], registration: "approval", beginnerFriendly: true,  source: "manual", signupUrl: "https://piefed.social/auth/register", description: "Vlajkový PieFed (alternativa k Redditu).", descriptionEn: "The flagship PieFed (a Reddit alternative)." },
];
